export const JsonFile = () => [
  { id: 1, name: "Aarav", position: "Developer", salary: 50000 },
  { id: 2, name: "Neha", position: "Designer", salary: 45000 },
  { id: 3, name: "Rohit", position: "Tester", salary: 40000 },
  { id: 4, name: "Priya", position: "HR", salary: 42000 },
  { id: 5, name: "Ankit", position: "Developer", salary: 52000 },
  { id: 6, name: "Pooja", position: "QA Engineer", salary: 41000 },
  { id: 7, name: "Rahul", position: "Manager", salary: 65000 },
  { id: 8, name: "Kavya", position: "UI Designer", salary: 46000 },
  { id: 9, name: "Vikas", position: "Backend Developer", salary: 58000 },
  { id: 10, name: "Simran", position: "Content Writer", salary: 35000 },

  { id: 11, name: "Amit", position: "DevOps Engineer", salary: 60000 },
  { id: 12, name: "Riya", position: "Business Analyst", salary: 48000 },
  { id: 13, name: "Suresh", position: "Support Engineer", salary: 39000 },
  { id: 14, name: "Nidhi", position: "HR Executive", salary: 43000 },
  { id: 15, name: "Manish", position: "Team Lead", salary: 70000 },
  { id: 16, name: "Sneha", position: "Tester", salary: 42000 },
  { id: 17, name: "Deepak", position: "Full Stack Developer", salary: 62000 },
  { id: 18, name: "Ishita", position: "UI Developer", salary: 47000 },
  { id: 19, name: "Karan", position: "Product Manager", salary: 75000 },
  { id: 20, name: "Alka", position: "Accountant", salary: 44000 },

  { id: 21, name: "Mohit", position: "Developer", salary: 54000 },
  { id: 22, name: "Payal", position: "Recruiter", salary: 41000 },
  { id: 23, name: "Gaurav", position: "System Admin", salary: 56000 },
  { id: 24, name: "Meena", position: "Office Admin", salary: 38000 },
  { id: 25, name: "Naveen", position: "Tech Lead", salary: 72000 },
  { id: 26, name: "Swati", position: "UX Researcher", salary: 49000 },
  { id: 27, name: "Harsh", position: "Intern", salary: 25000 },
  { id: 28, name: "Anjali", position: "Frontend Developer", salary: 53000 },
  { id: 29, name: "Sanjay", position: "Operations Manager", salary: 68000 },
  { id: 30, name: "Pankaj", position: "Database Admin", salary: 60000 },

  { id: 31, name: "Tanya", position: "Marketing Executive", salary: 42000 },
  { id: 32, name: "Vivek", position: "Security Analyst", salary: 65000 },
  { id: 33, name: "Rekha", position: "HR Manager", salary: 70000 },
  { id: 34, name: "Ashish", position: "Cloud Engineer", salary: 67000 },
  { id: 35, name: "Komal", position: "SEO Specialist", salary: 39000 },
  { id: 36, name: "Rakesh", position: "Network Engineer", salary: 58000 },
  { id: 37, name: "Shalini", position: "Scrum Master", salary: 72000 },
  { id: 38, name: "Nitin", position: "Mobile App Developer", salary: 61000 },
  { id: 39, name: "Preeti", position: "Graphic Designer", salary: 45000 },
  { id: 40, name: "Yogesh", position: "Technical Support", salary: 37000 },

  { id: 41, name: "Ayesha", position: "Data Analyst", salary: 64000 },
  { id: 42, name: "Imran", position: "AI Engineer", salary: 80000 },
  { id: 43, name: "Farhan", position: "ML Engineer", salary: 78000 },
  { id: 44, name: "Saba", position: "HR Assistant", salary: 36000 },
  { id: 45, name: "Zoya", position: "QA Lead", salary: 62000 },
  { id: 46, name: "Ritu", position: "Admin Executive", salary: 39000 },
  { id: 47, name: "Kapil", position: "Sales Manager", salary: 68000 },
  { id: 48, name: "Monika", position: "Customer Success", salary: 43000 },
  { id: 49, name: "Umesh", position: "IT Support", salary: 40000 },
  { id: 50, name: "Divya", position: "Project Coordinator", salary: 52000 },
];
